# Códigos de error

Los siguientes son los códigos de error establecidos por el protocolo 3-D Secure, con su respectiva descripción e instrucción de qué hacer en caso de presentarse.

 Código  | Descripción                                            | Instrucción                                        |
---------|--------------------------------------------------------|----------------------------------------------------|
 101     | Mensaje recibido no válido                             | Este error indica que el mensaje obtenido en un mensaje en el campo **messageType** no es válido, es inapropiado o no se reconoce. Si se presenta este error debe consultar al equipo de desarrollo y enviar el reporte completo del error para evaluar por qué se presentó y cómo solucionarlo.                                                                                                          |
 102     | Número de versión del mensaje no admitido              | Este error indica que la versión del protocolo recibida en el campo **messageVersion** de un mensaje no está soportada. Si se presenta este error debe consultar al equipo de desarrollo y enviar el reporte completo del error para evaluar por qué se presentó y cómo solucionarlo.      |
 103     | Se superó el límite de mensajes enviados               | Este error se presenta cuando un componente sobrepasa el límite de mensajes que puede enviar en un rango determinado de tiempo, se recomienda hacer un nuevo intento de autenticación  más tarde.                                                                                   |
 201     | Falta un elemento de datos requerido                   | Este error de validación se presenta cuando un dato es requerido para poder procesar un mensaje y no está presente. Cuando ocurra este error, el servicio lanzará el nombre del campo faltante, se recomienda lanzar de nuevo la petición de autenticación agregando este dato que está ausente.                                                                                                                           |
 202     | Extensión de mensaje crítica no reconocida             | El campo **messageExtension** tiene un elemento llamado “criticalityIndicator”, y un "ID" que lo identifica, este elemento indica si el destinatario debe comprender el contenido de la extensión para interpretar el mensaje completo. Este error se presenta cuando tal ID no logra identificarse.                                                                                                         |
 203     | El formato de uno o más elementos de datos es inválido | Este es un error de validación del formato en cómo se enviaron los elementos de un mensaje, el error indica el o los campos erróneos, se recomienda enviar de nuevo la solicitud de autenticación con tales datos corregidos.                                                                 |
 204     | Elemento de datos duplicado                            | Este error indica que se están enviando datos repetidos en un mensaje, revise los datos enviados como petición, elimine los elementos repetidos, y vuelva a enviar una petición.                                                                                                          |
 301     | ID de transacción no reconocido                        | Este error se presenta cuando el identificador de una transacción no es reconocido o se encuentra duplicado. Para obtener más información de esta transacción puede comunicarse con el emisor para comprobar el identificador.                                                             |
 302     | Fallo de descifrado de datos                           | Este es un error técnico donde no se logra hacer un proceso requerido de desciframiento de un dato. Si se presenta este error debe consultar al equipo de desarrollo y enviar el reporte completo del error para evaluar por qué se presentó y cómo solucionarlo.                             |
 303     | Acceso denegado, endpoint inválido                     | Este error puede indicar que no tiene permisos para acceder a un punto del servicio o que también puede deberse a una redirección inválida. Si se presenta este error debe consultar al equipo de desarrollo y enviar el reporte completo del error para evaluar por qué se presentó y cómo solucionarlo.                                                                                                          |
 304     | Código ISO no válido                                   | Este error se presenta cuando el código ISO referenciado en el campo **mcc**, no se encuentra en las listas de valores soportados por el ACS o es uno de los códigos ISO excluídos. Para este error puede dirigirse a la lista de países o monedas según corresponda, y revise si el código fallido se encuentra excluído, si no es así puede contactarse con el equipo de desarrollo, para verificar el flujo de la autenticación y a qué se debe el error.                                                                    |
 305     | Datos de transacción no válidos                        | Este error puede deberse a varias razones según la la traza de la autenticación, puede ser que el número de la tarjeta en el campo **acctNumber**, no se encuentra en el rango del emisor que procesó la transacción, para verificar esto puede dirigirse a la consola, al detalle del emisor correspondiente, luego a la sección **Gestionar rangos de tarjetas**, y revise si la tarjeta está dentro de uno de los rangos de la lista. También, puede deberse a que el ID de la transacción ya fue procesado.                             |
 306     | Código de categoría de comerciante (MCC) inválido      | En este error el MCC aportado en el mensaje, no es válido para el sistema de pago, probablemente se encuentra una inconsistencia, puede corroborar el MCC en la consola, menú **Códigos de categoría del comercio**, busque el código dado y verifique la información, si está correcta puede comunicarse con el emisor para obtener más información del error.                                                      |
 307     | Número de serie no válido                              | Este error indica que el dato ingresado en el campo **serialNum** no fue encontrado o es muy antiguo, puede verificar esta información con el emisor correspondiente.      |
 402     | Transacción expirada                                   | Este error ocurre cuando se agota el tiempo de espera para finalizar una transacción. Indica que la sesión de pago expiró, por lo cual se debe generar una nueva.     |
 403     | Falla transitoria del sistema                          | Este error se presenta por ejemplo cuando el procesamiento se está ejecutando de forma lenta, lo cual ocasiona fallos. Se recomienda generar reportes de servicios que se estén ejecutando regularmente de forma lenta y comunicarlos al equipo de desarrollo para buscar optimizaciones y mejoras en el procesamiento de los datos.                                                                              |
 404     | Fallo permanente del sistema                           | Este error se presenta cuando una parte esencial del flujo no está funcionando o no puede ser accedida, por ejemplo la base de datos para hacer consultas y guardar la información entrante. Se recomienda generar reportes del error y comunicarlos al equipo de desarrollo para verificar y solucionar.                                                                                                            |
 405     | Fallo de conexión del sistema                          | Este error suele presentarse cuando no se logra establecer conexión por ejemplo con un servicio externo requerido, por ejemplo para la generación de OTP o para enviar una solicitud de autenticación desacoplada al emisor. Se recomienda comunicarse con un representante del servicio que esté fallando para verificar y dar solución a esta situación.                                                          |
